package com.fitincontact.exonDoc.enums;

public enum CharPlaceType {

    OBJ_L_CURLY_BRACKET,
    OBJ_R_CURLY_BRACKET,//END
    OBJ_WHITE_SPACE_1,
    OBJ_MEMBER_CHARACTER_FIRST,
    OBJ_MEMBER_CHARACTER_AFTER_FIRST,
    OBJ_WHITE_SPACE_2,
    OBJ_COLON,
    OBJ_WHITE_SPACE_3,

    ARR_L_SQUARE_BRACKET,
    ARR_R_SQUARE_BRACKET,//END
    ARR_WHITE_SPACE,

    STR_L_APOSTROPHE,
    STR_R_APOSTROPHE,//END
    STR_CHARACTER,

    NUM_DIGIT_FIRST,
    NUM_DIGIT_AFTER_FIRST,
    NUM_WHITE_SPACE,//END

    DATE_L_QUOTATION_MARKS,
    DATE_R_QUOTATION_MARKS,//END
    DATE_CHARACTER,

    PATH_L_GRAVE_ACCENT,
    PATH_R_GRAVE_ACCENT,
    PATH_CHARACTER,

    BOOL_TRUE_T,
    BOOL_TRUE_R,
    BOOL_TRUE_U,
    BOOL_TRUE_E,

    BOOL_FALSE_F,
    BOOL_FALSE_A,
    BOOL_FALSE_L,
    BOOL_FALSE_S,
    BOOL_FALSE_E,

    BOOL_NIL_N,
    BOOL_NIL_I,
    BOOL_NIL_L,
    BOOL_WHITE_SPACE,

    ERROR,
    ;
}